" Generated by vim-plug
" Mon Apr 18 10:17:59 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufferline.nvim'].commit = '004cd5734fb21e39d48c1fb1469fa63e2797880b'
silent! let g:plugs['coc.nvim'].commit = '606f2765453539272359d41d5e68b1d266325e83'
silent! let g:plugs['gitsigns.nvim'].commit = 'eb7d40f68396dd2f470a139810a154e82820703d'
silent! let g:plugs['hop.nvim'].commit = '75f73d3959a0df7ef3642fd5138acdb1ce50fdc8'
silent! let g:plugs['indent-blankline.nvim'].commit = '045d9582094b27f5ae04d8b635c6da8e97e53f1d'
silent! let g:plugs['lualine.nvim'].commit = '18a07f790ed7ed1f11d1b130c02782e9dfd8dd7d'
silent! let g:plugs['minimap.vim'].commit = '3395cbd51bf042ef6d2cd714eb493eb7ed5fbb76'
silent! let g:plugs['neogit'].commit = 'c8dd268091ffcbcb673de59c5b37ff26a2eb24ed'
silent! let g:plugs['nord.nvim'].commit = '1fdad275596f85bdc36c525b14697ff3a4f08bdf'
silent! let g:plugs['nvim-spectre'].commit = '345e5dd57773e2b4b425a2515c831108b9808a0f'
silent! let g:plugs['nvim-tree.lua'].commit = '84993e9e9fbc1a3bd851a52f13575786ec6f5262'
silent! let g:plugs['nvim-treesitter'].commit = '4542402e34568eb607059e3ff6a3594aaca850fd'
silent! let g:plugs['nvim-ts-rainbow'].commit = '04284dc97eac0d0ecfea68e10be824d1a6585de0'
silent! let g:plugs['nvim-web-devicons'].commit = '09e62319974d7d7ec7e53b974724f7942470ef78'
silent! let g:plugs['plenary.nvim'].commit = '9069d14a120cadb4f6825f76821533f2babcab92'
silent! let g:plugs['splitjoin.vim'].commit = 'dbcd3069fb2b4ecfdd964c1e93aa59fcf7f850b6'
silent! let g:plugs['telescope.nvim'].commit = '831f76a809d9f09724d9f3825a3660ed714470d9'
silent! let g:plugs['toggleterm.nvim'].commit = '5733b24c684d202f978ccedca4a8c7571889bf28'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-camelsnek'].commit = '3fef4df12b659ade6646c96e58e55a2d81512ef6'
silent! let g:plugs['vim-coffee-script'].commit = '28421258a8dde5a50deafbfc19cd9873cacfaa79'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-gh-line'].commit = 'd2185b18883b911a21b684d4bb9d26f6a41b62f4'
silent! let g:plugs['vim-rails'].commit = 'd38f1bf8575b920042153689492721b80252ae41'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['vim-slim'].commit = 'f0758ea1c585d53b9c239177a8b891d8bbbb6fbb'
silent! let g:plugs['vim-snippets'].commit = 'a0f550c77ac4c815ee6ab42a1d88bf2ba905ad67'
silent! let g:plugs['vim-surround'].commit = '81fc0ec460dd8b25a76346e09aecdbca2677f1a7'
silent! let g:plugs['vim-test'].commit = '2240d7a4b868cb594b7d83544e1b6db4df806e5e'
silent! let g:plugs['yaml.nvim'].commit = '155c23de8f99fdb424f8aa713bcb993cc2538c6c'

PlugUpdate!

