" Generated by vim-plug
" Tue Mar 29 09:10:07 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufferline.nvim'].commit = 'd5904e8a3434acb151a4948b1b3d4760a2a12bb1'
silent! let g:plugs['coc.nvim'].commit = 'e913d32ad234b8778b8e0c14631edf5396e9a4e2'
silent! let g:plugs['gitsigns.nvim'].commit = '5c487a804e462c284c159c800a803b8e0294d0a4'
silent! let g:plugs['hop.nvim'].commit = '75f73d3959a0df7ef3642fd5138acdb1ce50fdc8'
silent! let g:plugs['indent-blankline.nvim'].commit = '9915d46ba9361784c70036bb7259c436249e5b0c'
silent! let g:plugs['lualine.nvim'].commit = '88a44ade818f9ee7ba730aa4096250e22b243808'
silent! let g:plugs['minimap.vim'].commit = 'c8ea2a5550b95b007631bc83908c48a3368eb57c'
silent! let g:plugs['neogit'].commit = 'f30879799f7c19d0047c6f3d3a86b818eaf0f201'
silent! let g:plugs['nord.nvim'].commit = '1fdad275596f85bdc36c525b14697ff3a4f08bdf'
silent! let g:plugs['nvim-spectre'].commit = '208d983e9bab4d0eb98b4642636e1b4f41c5280a'
silent! let g:plugs['nvim-tree.lua'].commit = '2457e141ae5c2e9c5d94a9550b37b421d25cfff1'
silent! let g:plugs['nvim-treesitter'].commit = 'f448a78057290cca9c70c4065819da96103f3dee'
silent! let g:plugs['nvim-ts-rainbow'].commit = '0594067ae677a192a94e383c25a93ac1c3a844d1'
silent! let g:plugs['nvim-web-devicons'].commit = '4415d1aaa56f73b9c05795af84d625c610b05d3b'
silent! let g:plugs['plenary.nvim'].commit = '14dfb4071022b22e08384ee125a5607464b6d397'
silent! let g:plugs['splitjoin.vim'].commit = '452d1359fb14731a316be49fb446a05d2c7d2f71'
silent! let g:plugs['telescope.nvim'].commit = 'd331433ed82f68beb54135a5b7f9ef02e90a0ade'
silent! let g:plugs['toggleterm.nvim'].commit = 'e97d0c1046512e975a9f3fa95afe98f312752b1c'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-camelsnek'].commit = '3fef4df12b659ade6646c96e58e55a2d81512ef6'
silent! let g:plugs['vim-coffee-script'].commit = '28421258a8dde5a50deafbfc19cd9873cacfaa79'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-gh-line'].commit = 'd2185b18883b911a21b684d4bb9d26f6a41b62f4'
silent! let g:plugs['vim-rails'].commit = 'de73f6d1b0bf1b2af2d576f3420fc861af14769f'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['vim-slim'].commit = 'f0758ea1c585d53b9c239177a8b891d8bbbb6fbb'
silent! let g:plugs['vim-snippets'].commit = '4e1d1456fd7d1d5d6cff256578a3e3bbeeb24e62'
silent! let g:plugs['vim-surround'].commit = 'baf89ad26488f6a7665d51b986f5c7ad2d22b30b'
silent! let g:plugs['vim-test'].commit = '16a3b6da1bab42473d42d7e02d89d549d7a5e138'
silent! let g:plugs['yaml.nvim'].commit = '155c23de8f99fdb424f8aa713bcb993cc2538c6c'

PlugUpdate!

