" Generated by vim-plug
" Tue Jan 25 15:01:33 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufferline.nvim'].commit = '7451dfc97d28e6783dbeb1cdcff12619a9323c98'
silent! let g:plugs['coc.nvim'].commit = '2556c26f5ec27704a585f30cf5b0186a1d836aa3'
silent! let g:plugs['gitsigns.nvim'].commit = 'f43cee333fdfeb27aae86bab73a38c5885d5c7f4'
silent! let g:plugs['hop.nvim'].commit = 'e3c9fc3ab1e1db6bfb4f19377c53d0e457e0e2e9'
silent! let g:plugs['indent-blankline.nvim'].commit = '2e35f7dcdc72f39b37c21e43cdb538d7a41c7e07'
silent! let g:plugs['lualine.nvim'].commit = '9208bae98fd5d1ab6145868a8c48bfee53c1a499'
silent! let g:plugs['minimap.vim'].commit = 'e5707899509be893a530d44b9bed8cff4cda65e1'
silent! let g:plugs['neogit'].commit = '3086635873ae37fc8e28d7de55c2969682104a7d'
silent! let g:plugs['nord.nvim'].commit = '2ec29eda54f5bbc8856794361847729b0f724095'
silent! let g:plugs['nvim-spectre'].commit = '4a4cf2c981b077055ef7725959d13007e366ba23'
silent! let g:plugs['nvim-tree.lua'].commit = '2dfed89af7724f9e71d2fdbe3cde791a93e9b9e0'
silent! let g:plugs['nvim-treesitter'].commit = 'c08821bb79bd3f0869317dbdd524bd74c345be31'
silent! let g:plugs['nvim-ts-rainbow'].commit = '38eb126412723fa4c3bfd137c1a3a811faf67eb5'
silent! let g:plugs['nvim-web-devicons'].commit = '634e26818f2bea9161b7efa76735746838971824'
silent! let g:plugs['plenary.nvim'].commit = '563d9f6d083f0514548f2ac4ad1888326d0a1c66'
silent! let g:plugs['splitjoin.vim'].commit = '452d1359fb14731a316be49fb446a05d2c7d2f71'
silent! let g:plugs['telescope.nvim'].commit = '0011b1148d3975600f5a9f0be8058cdaac4e30d9'
silent! let g:plugs['toggleterm.nvim'].commit = '0ae65ceaca2a62e4342ed632c8d1b7861e0e9ac8'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-camelsnek'].commit = '3fef4df12b659ade6646c96e58e55a2d81512ef6'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-gh-line'].commit = 'd2185b18883b911a21b684d4bb9d26f6a41b62f4'
silent! let g:plugs['vim-rails'].commit = 'de73f6d1b0bf1b2af2d576f3420fc861af14769f'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['vim-slim'].commit = 'f0758ea1c585d53b9c239177a8b891d8bbbb6fbb'
silent! let g:plugs['vim-snippets'].commit = 'cbad57e5d0304198503648b5416ea28d2d1d437a'
silent! let g:plugs['vim-surround'].commit = 'aeb933272e72617f7c4d35e1f003be16836b948d'
silent! let g:plugs['vim-test'].commit = '2ace9a12253140f1bdf4318a46ca9076658dd147'
silent! let g:plugs['yaml.nvim'].commit = 'ddc98c103752f25d6b69bb0272d659ffeba9c4db'

PlugUpdate!

