" Generated by vim-plug
" Wed Aug 17 10:21:22 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bufferline.nvim'].commit = '004cd5734fb21e39d48c1fb1469fa63e2797880b'
silent! let g:plugs['coc.nvim'].commit = '420c45907ca81d3b7959051b928f8c799c9c32b3'
silent! let g:plugs['conjure'].commit = '08236a13164a948fe403f34fe1f593ead0a3c6fe'
silent! let g:plugs['ctrlsf.vim'].commit = '40cdf404b39911cdc4c5432e65247311ee8cd8ac'
silent! let g:plugs['gitsigns.nvim'].commit = '29468d89e71a0cd04aeb750fcfe75c3163347adf'
silent! let g:plugs['hop.nvim'].commit = '75f73d3959a0df7ef3642fd5138acdb1ce50fdc8'
silent! let g:plugs['indent-blankline.nvim'].commit = 'c15bbe9f23d88b5c0b4ca45a446e01a0a3913707'
silent! let g:plugs['lualine.nvim'].commit = 'c0510ddec86070dbcacbd291736de27aabbf3bfe'
silent! let g:plugs['minimap.vim'].commit = '3801d9dfaa5431e7b83ae6f98423ac077d9f5c3f'
silent! let g:plugs['neogit'].commit = '05386ff1e9da447d4688525d64f7611c863f05ca'
silent! let g:plugs['nord.nvim'].commit = '6bfb0f7d6e4faf7cddedd34489efe2d2f586325c'
silent! let g:plugs['nvim-tree.lua'].commit = '09a51266bca28dd87febd63c66bdbd74f7764a63'
silent! let g:plugs['nvim-treesitter'].commit = '116c72f5c2e4e63bbf0b7d698f9d35e36848605a'
silent! let g:plugs['nvim-ts-rainbow'].commit = '1e904f6d1b41adb9d3b87df2108dc4a315a72379'
silent! let g:plugs['nvim-web-devicons'].commit = '2d02a56189e2bde11edd4712fea16f08a6656944'
silent! let g:plugs['plenary.nvim'].commit = '31807eef4ed574854b8a53ae40ea3292033a78ea'
silent! let g:plugs['splitjoin.vim'].commit = 'ab9d5cd1fba6d3f1acaf25a1b31d4f6ff961c839'
silent! let g:plugs['telescope.nvim'].commit = 'd793de0f12d874c463e81edabee741b802c1a37a'
silent! let g:plugs['toggleterm.nvim'].commit = '5733b24c684d202f978ccedca4a8c7571889bf28'
silent! let g:plugs['vim-better-whitespace'].commit = '1b22dc57a2751c7afbc6025a7da39b7c22db635d'
silent! let g:plugs['vim-camelsnek'].commit = '3fef4df12b659ade6646c96e58e55a2d81512ef6'
silent! let g:plugs['vim-coffee-script'].commit = '28421258a8dde5a50deafbfc19cd9873cacfaa79'
silent! let g:plugs['vim-commentary'].commit = '3654775824337f466109f00eaf6759760f65be34'
silent! let g:plugs['vim-gh-line'].commit = '622d7812a268b3e869e8f8c7ee5871e7ee98ab43'
silent! let g:plugs['vim-rails'].commit = '936c4a170bf25dda16cb091537c8377d98f38525'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['vim-slim'].commit = 'f0758ea1c585d53b9c239177a8b891d8bbbb6fbb'
silent! let g:plugs['vim-snippets'].commit = '5aa8330b67a0b2e4c759950a9b16a75e5eda9c90'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-test'].commit = 'dfb99b8867556ea63e67f4a7cbc2ee10dda4b3be'
silent! let g:plugs['vim-visual-multi'].commit = 'e23b98a8852255766e54bf7723a9d61fb5ab3143'
silent! let g:plugs['yaml.nvim'].commit = 'ee6143a61325ae06938fd210a86406bef6093471'

PlugUpdate!

