" Generated by vim-plug
" Sun Jan  9 16:33:16 2022
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['FixCursorHold.nvim'].commit = '0e4e22d21975da60b0fd2d302285b3b603f9f71e'
silent! let g:plugs['bufferline.nvim'].commit = '17efb4c834daf4eea96f18753541485ed05baa6e'
silent! let g:plugs['coq.artifacts'].commit = '4f8cbf0e5af91a63a5763f45326a7752b749ad6d'
silent! let g:plugs['coq.thirdparty'].commit = '77fab329a1e251b4a678f65e8080fc43bd3b3216'
silent! let g:plugs['coq_nvim'].commit = '608fb7d5fa34127131011bd1973ec4c5fa70152f'
silent! let g:plugs['gitsigns.nvim'].commit = 'c18fc65c77abf95ac2e7783b9e7455a7a2fab26c'
silent! let g:plugs['hop.nvim'].commit = 'e3c9fc3ab1e1db6bfb4f19377c53d0e457e0e2e9'
silent! let g:plugs['indent-blankline.nvim'].commit = '0f8df7e43f0cae4c44e0e8383436ad602f333419'
silent! let g:plugs['lualine.nvim'].commit = 'fd8fa5ddd823e15721ddec560ea61e7372e746a7'
silent! let g:plugs['neogit'].commit = '46ee1c5bbbc6aee521ff6f912fb72e8a6b333812'
silent! let g:plugs['nord.nvim'].commit = 'ab4ae54c932a3f1b16b63e727265cfca70be8d65'
silent! let g:plugs['nvim-autopairs'].commit = '5348e4a778ebdf42126a54fb5a933a98612df6cb'
silent! let g:plugs['nvim-lspconfig'].commit = 'c7081e00fa8100ee099c16e375f3e5e838cbf1db'
silent! let g:plugs['nvim-spectre'].commit = '4a4cf2c981b077055ef7725959d13007e366ba23'
silent! let g:plugs['nvim-tree.lua'].commit = '0a2f6b0b6ba558a88c77a6b262af647760e6eca8'
silent! let g:plugs['nvim-treesitter'].commit = 'f9179db8de68d4ecfdde0881ab2e67b2b76a06a8'
silent! let g:plugs['nvim-ts-rainbow'].commit = '54ee09f540935c604c9a3d4aed83b7f5314f2caa'
silent! let g:plugs['nvim-web-devicons'].commit = 'ac71ca88b1136e1ecb2aefef4948130f31aa40d1'
silent! let g:plugs['plenary.nvim'].commit = '563d9f6d083f0514548f2ac4ad1888326d0a1c66'
silent! let g:plugs['splitjoin.vim'].commit = '452d1359fb14731a316be49fb446a05d2c7d2f71'
silent! let g:plugs['telescope.nvim'].commit = 'f06dd06bb1143caa779e492ca37e5f985f0c6157'
silent! let g:plugs['trouble.nvim'].commit = '20469be985143d024c460d95326ebeff9971d714'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-camelsnek'].commit = '3fef4df12b659ade6646c96e58e55a2d81512ef6'
silent! let g:plugs['vim-commentary'].commit = '627308e30639be3e2d5402808ce18690557e8292'
silent! let g:plugs['vim-gh-line'].commit = 'd2185b18883b911a21b684d4bb9d26f6a41b62f4'
silent! let g:plugs['vim-rails'].commit = '3bac0233a49d2a00805c66bf17d3e2ea114b05d1'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-sexp'].commit = '14464d4580af43424ed8f2614d94e62bfa40bb4d'
silent! let g:plugs['vim-sexp-mappings-for-regular-people'].commit = '7c3de2f13422fb4b62b4c34a660532c7b3d240c7'
silent! let g:plugs['vim-slim'].commit = 'f0758ea1c585d53b9c239177a8b891d8bbbb6fbb'
silent! let g:plugs['vim-surround'].commit = 'aeb933272e72617f7c4d35e1f003be16836b948d'
silent! let g:plugs['vim-test'].commit = '1efc3def36eff8ac12ddb1f25837ef6101531047'
silent! let g:plugs['yaml.nvim'].commit = 'ddc98c103752f25d6b69bb0272d659ffeba9c4db'

PlugUpdate!

